In [62]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [63]:
df = pd.read_csv(r"Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [64]:
df.drop('Id',axis=1,inplace=True)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [65]:
le = LabelEncoder()
df['Species']= le.fit_transform(df['Species'])
df['Species'].unique()

array([0, 1, 2])

In [66]:
X=df.iloc[:,:4]
y=df.iloc[:,4:]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=123)

In [68]:
KNN = KNeighborsClassifier(n_neighbors = 5)
KNN.fit(X_train,y_train)
y_prediction=KNN.predict(X_test)

e:\github\ML-LAB\.venv\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [69]:
print('The Accuracy Score Of KNN Algorithm: ', accuracy_score(y_test,y_prediction))

The Accuracy Score Of KNN Algorithm:  0.9777777777777777


In [70]:
class_names=["Iris-setosa","Iris-virginica","Iris-versicolor"]
print(confusion_matrix(y_test, y_prediction))

[[18  0  0]
 [ 0  9  1]
 [ 0  0 17]]


: 

In [ ]:
import numpy as np
np.sum()

: 